# Generated by Django 4.1.3 on 2022-11-14 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0002_create_workout'),
    ]

    operations = []
