# Generated by Django 4.1.3 on 2022-11-14 12:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_create_workout'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('location', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('caption', models.TextField()),
                ('music_link', models.URLField(blank=True, null=True)),
                ('date_of_publication', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ManyToManyField(blank=True, to='workouts.workout')),
            ],
        ),
    ]
