# Generated by Django 4.1.3 on 2022-11-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_create_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-date_of_publication',)},
        ),
    ]
