# Generated by Django 4.1.3 on 2022-11-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_date_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
