# Generated by Django 4.1.1 on 2022-10-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_introduction', '0002_alter_company_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='open_positions',
            field=models.CharField(choices=[('DevOps', 'DevOps'), ('BackEnd', 'BackEnd'), ('FrontEnd', 'FrontEnd'), ('QA', 'QA')], max_length=15, null=True),
        ),
    ]
