# Generated by Django 4.1.1 on 2022-10-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_introduction', '0008_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
