# Generated by Django 4.1.1 on 2022-10-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_introduction', '0009_alter_department_options_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
