# Generated by Django 4.1.2 on 2022-10-29 09:07

import django.core.validators
from django.db import migrations, models
import prep_exam02.games.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = []
