# Generated by Django 4.1.1 on 2022-10-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_create_comment_and_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocomment',
            options={'ordering': ('-publication_date_and_time',)},
        ),
    ]
