# Generated by Django 4.1.1 on 2022-10-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_photo'),
        ('common', '0003_alter_photocomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='photos.photo'),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='photos.photo'),
        ),
    ]
