# Generated by Django 4.1.2 on 2022-10-28 08:32

import django.core.validators
from django.db import migrations, models
import prep_exam01.profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = []
