# Generated by Django 4.1.2 on 2022-10-14 09:19

import demo003.web.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_student_personal_info_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='personal_info',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[demo003.web.validations.all_decimal]),
        ),
    ]
