# Generated by Django 4.1.2 on 2022-10-08 10:37

from django.db import migrations
from django.utils.text import slugify


def add_slug(apps, schema_editor):
    School = apps.get_model('web', 'School')

    schools = School.objects.all()

    for school in schools:
        school.slug = slugify(school.name)

    School.objects.bulk_update(schools, ['slug'])


def delete_slug(apps, schema_editor):
    School = apps.get_model('web', 'School')

    schools = School.objects.all()

    for school in schools:
        school.slug = None

    School.objects.bulk_update(schools, ['slug'])


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0003_school_slug'),
    ]

    operations = [
        migrations.RunPython(add_slug, delete_slug)
    ]
