# Generated by Django 4.1.2 on 2022-10-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_autocomplete_slug_in_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='postal_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(default='none', unique=True),
            preserve_default=False,
        ),
    ]
