# Generated by Django 4.1.2 on 2022-10-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_city_postal_code_alter_student_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
