# Generated by Django 4.1.2 on 2022-10-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_address_options_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='web.city'),
            preserve_default=False,
        ),
    ]
