# Generated by Django 4.1.2 on 2022-10-10 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
