# Generated by Django 4.1.1 on 2022-10-17 09:33

import django.core.validators
from django.db import migrations, models
import exercises_for_web.photos.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
