# Generated by Django 4.1.2 on 2022-10-19 09:39

from django.db import migrations, models
import forms_demo_part2.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_animal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.IntegerField(null=True, validators=[forms_demo_part2.web.validators.ValueInRangeValidator(1, 20)]),
        ),
    ]
