# Generated by Django 4.1.2 on 2022-10-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_animal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
