# Generated by Django 4.1.3 on 2022-11-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('experience_years', models.PositiveIntegerField()),
                ('good_skills', models.BooleanField(null=True)),
            ],
        ),
    ]
