# Generated by Django 4.1.1 on 2022-10-11 12:17

from django.db import migrations, models
import petstagram.photos.validations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_create_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='staticfiles/images/', validators=[petstagram.photos.validations.validate_image]),
        ),
    ]
