# Generated by Django 4.1.1 on 2022-11-10 09:36

from django.db import migrations



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = []
