# Generated by Django 4.1.1 on 2022-11-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
