# Generated by Django 4.1.2 on 2022-10-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_city_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
