# Generated by Django 4.1.2 on 2022-10-09 09:48

import demo01.core.validate_first_char_is_upper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=40, unique=True, validators=[demo01.core.validate_first_char_is_upper.first_upper]),
        ),
    ]
