# Generated by Django 4.1.2 on 2022-10-10 13:36

import demo002.core.phone_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[demo002.core.phone_validator.validate_phone_number]),
        ),
    ]
