# Generated by Django 4.1.2 on 2022-10-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_employees_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_full_time',
            field=models.BooleanField(null=True),
        ),
    ]
