# Generated by Django 4.1.2 on 2022-10-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_employees_is_full_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employees',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Regular', 'Regular'), ('Senior', 'Senior')], max_length=20),
        ),
    ]
