# Generated by Django 4.1.2 on 2022-10-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_department_alter_employees_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='web.department'),
            preserve_default=False,
        ),
    ]
