# Generated by Django 4.1.2 on 2022-10-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_employees_options_department_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
    ]
