# Generated by Django 4.1.1 on 2022-10-21 08:15

from django.db import migrations
from django.utils.text import slugify


def add_slug(apps, schema_editor):
    Pet = apps.get_model('pets', 'Pet')

    pets = Pet.objects.all()

    for pet in pets:
        pet.slug = slugify(f'{pet.name}-{pet.id}')

    Pet.objects.bulk_update(pets, ['slug'])


def delete_slug(apps, schema_editor):
    Pet = apps.get_model('pets', 'Pet')

    pets = Pet.objects.all()

    for pet in pets:
        pet.slug = None

    Pet.objects.bulk_update(pets, ['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_create_pet'),
    ]

    operations = [
        migrations.RunPython(add_slug, delete_slug)
    ]
