# Generated by Django 4.1.2 on 2022-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('Mammals', 'Mammals'), ('Fishes', 'Fishes'), ('Birds', 'Birds'), ('Reptiles', 'Reptiles')], max_length=30)),
            ],
        ),
    ]
