# Generated by Django 4.1.2 on 2022-10-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_create_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('Mammals', 'Mammals'), ('Fishes', 'Fishes'), ('Birds', 'Birds'), ('Reptiles', 'Reptiles')], default='Unspecified', max_length=30),
        ),
    ]
