# Generated by Django 4.1.2 on 2022-10-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_type_remove_animal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='web.type'),
            preserve_default=False,
        ),
    ]
