# Generated by Django 4.1.2 on 2022-10-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_employees_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='level',
            field=models.CharField(default='Junior', max_length=20),
            preserve_default=False,
        ),
    ]
