# Generated by Django 4.1.2 on 2022-10-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_employees_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
