# Generated by Django 4.1.2 on 2022-10-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.creditcard'),
        ),
    ]
