# Generated by Django 4.1.2 on 2022-10-07 10:24

from django.db import migrations, models
import models_demos.core.review_validator


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='review',
            field=models.TextField(validators=[models_demos.core.review_validator.validate_review_length]),
        ),
    ]
