# Generated by Django 4.1.1 on 2022-10-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_create_pet'),
    ]

    operations = []
