# Generated by Django 4.1.1 on 2022-10-21 09:21

from django.db import migrations, models
import petstagram.photos.validations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images', validators=[petstagram.photos.validations.validate_image]),
        ),
    ]
