# Generated by Django 4.1.1 on 2022-10-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_introduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
