# Generated by Django 4.1.1 on 2022-10-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates_introduction', '0005_project_alter_company_month_income_employee_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='templates_introduction.employee')),
            ],
        ),
    ]
