# Generated by Django 4.1.1 on 2022-10-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_introduction', '0007_rename_employeeaddress_creditcard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
