# Generated by Django 4.1.2 on 2022-10-23 11:42

from django.db import migrations, models
import my_music_app.albums.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = []
