# Generated by Django 4.1.3 on 2022-11-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_create_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='link_to_image',
            field=models.URLField(max_length=500),
        ),
    ]
